<a href="https://colab.research.google.com/github/poddubnyoleg/nondualbot/blob/master/train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.callbacks import ModelCheckpoint
from keras.utils import np_utils
import keras.backend as K
import sys

Using TensorFlow backend.


In [2]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
file = open('/content/drive/My Drive/nondualbot/i_am_that.txt', 'r') 
data = file.read() 

In [4]:
data[:100]

'That which permeates all, which nothing transcends and which, like the universal space around us, fi'

In [0]:
chars = sorted(list(set(data)))
char_to_int = dict((c, i) for i, c in enumerate(chars))
int_to_char = dict((i, c) for i, c in enumerate(chars))

In [6]:

n_chars = len(data)
n_vocab = len(chars)
print("Total Characters: ", n_chars)
print("Total Vocab: ", n_vocab)

Total Characters:  988168
Total Vocab:  55


For each chunk of data [seq_length] we take one-hot-encoded dataX array and dataY array (same but shifted +1)

In [0]:
seq_length = 100
overlapping_length = 30
dataX = []
dataY = []
cur_pos = 0
while cur_pos<n_chars-seq_length-1:
  seq_input = np_utils.to_categorical([char_to_int[char] for char in data[cur_pos:cur_pos + seq_length]], num_classes=n_vocab)
  seq_output = np_utils.to_categorical(char_to_int[data[cur_pos + seq_length+1]],num_classes=n_vocab)
  dataX.append(seq_input)
  dataY.append(seq_output)

  cur_pos+=10

In [8]:
dataY[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.], dtype=float32)

In [10]:
X = np.reshape(dataX, (len(dataX), seq_length, n_vocab))
print(X.shape)

(98807, 100, 55)


In [11]:
y = np.reshape(dataY, (len(dataY), n_vocab))
print(y.shape)

(98807, 55)


In [12]:
X.shape[1], X.shape[2], y.shape[1]

(100, 55, 55)

In [14]:
K.clear_session()

model = Sequential()
model.add(LSTM(256, input_shape=(X.shape[1], X.shape[2]), return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(256))
model.add(Dropout(0.2))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam')
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 100, 256)          319488    
_________________________________________________________________
dropout_1 (Dropout)          (None, 100, 256)          0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 256)               525312    
_________________________________________________________________
dropout_2 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 55)                14135     
Total params: 858,935
Trainable params: 858,935
Non-trainable params: 0
_________________________________________________________________


In [0]:
filepath="/content/drive/My Drive/nondualbot/weights-improvement-{epoch:02d}-{loss:.4f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='loss', verbose=1, save_best_only=True, mode='min')
callbacks_list = [checkpoint]

In [0]:
model.fit(X, y, epochs=50, batch_size=128, callbacks=callbacks_list)

Epoch 1/50
98807/98807 [==============================] - 329s 3ms/step - loss: 2.8212

Epoch 00001: loss improved from inf to 2.82120, saving model to /content/drive/My Drive/nondualbot/weights-improvement-01-2.8212.hdf5
Epoch 2/50
98807/98807 [==============================] - 332s 3ms/step - loss: 2.4894

Epoch 00002: loss improved from 2.82120 to 2.48943, saving model to /content/drive/My Drive/nondualbot/weights-improvement-02-2.4894.hdf5
Epoch 3/50
98807/98807 [==============================] - 328s 3ms/step - loss: 2.3343

Epoch 00003: loss improved from 2.48943 to 2.33435, saving model to /content/drive/My Drive/nondualbot/weights-improvement-03-2.3343.hdf5
Epoch 4/50
83968/98807 [========================>.....] - ETA: 50s - loss: 2.2294

In [0]:
# load the network weights
#filename = "weights-improvement-04-2.1211.hdf5"
#model.load_weights(filename)
#model.compile(loss='categorical_crossentropy', optimizer='adam')

In [32]:
[np.where(r==1)[0][0] for r in pattern]

[36,
 0,
 48,
 36,
 33,
 0,
 30,
 43,
 32,
 53,
 3,
 0,
 24,
 36,
 37,
 47,
 0,
 47,
 44,
 46,
 33,
 29,
 32,
 37,
 42,
 35,
 0,
 48,
 36,
 33,
 0,
 35,
 43,
 43,
 32,
 0,
 42,
 33,
 51,
 47,
 0,
 43,
 34,
 0,
 33,
 42,
 40,
 37,
 35,
 36,
 48,
 33,
 42,
 41,
 33,
 42,
 48,
 0,
 47,
 33,
 33,
 41,
 47,
 0,
 50,
 33,
 46,
 53,
 0,
 37,
 41,
 44,
 43,
 46,
 48,
 29,
 42,
 48,
 3,
 0,
 24,
 36,
 33,
 0,
 50,
 33,
 46,
 53,
 0,
 36,
 33,
 29,
 46,
 37,
 42,
 35,
 0,
 43,
 34,
 0]

In [63]:

# pick a random seed
start = np.random.randint(0, len(dataX)-1)
pattern = dataX[start]
pattern_flat = [np.where(r==1)[0][0] for r in pattern]
print("Seed:")
print("\"", ''.join([int_to_char[value] for value in pattern_flat]), "\"")
# generate characters
for i in range(100):

  prediction = model.predict(np.reshape(pattern, (1, 100, 55)), verbose=0)

  index = numpy.argmax(prediction)
  result = int_to_char[index]
  sys.stdout.write(result)
  pattern = np.append(pattern, [np_utils.to_categorical(index,num_classes=n_vocab)], axis=0)
  pattern = pattern[1:len(pattern)]
  #print("\nDone.")

Seed:
" ng time, you will come to see the light of awareness in all its clarity and the world will fade out  "
hvrsas o o hmras frm o ntin o slfe.Tee nt sefl hprsan frm o ntin nt sol hprslfa ogoe fre nt ntdsae f

In [0]:
pattern = dataX[start]
#pattern = np.append(pattern, np_utils.to_categorical(index,num_classes=n_vocab))

In [58]:
np.append(pattern, [np_utils.to_categorical(index,num_classes=n_vocab)], axis=0)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [57]:
patte

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.], dtype=float32)